<img src = "https://drive.google.com/uc?export=view&id=1XIxF92v5BOrpS63i6FMIXGddxAp8WSHd" alt = "Encabezado MLDS" width = "100%">  </img>

#**Quiz 5 : Estadística inferencial con *Python***
---

Este es un quiz para practicar las habilidades adquiridas usando *Python* en estadística inferencial. Utilizaremos el [dataset 80 Cereals](https://www.kaggle.com/crawford/80-cereals) de *Kaggle*. Para esto, previamente hemos realizado un proceso de limpieza y traducción adecuado para el ejercicio.

Este conjunto de datos cuenta con información nutricional de una muestra de 80 cereales:

| Variable | Definición	| Valores | 
| --- | --- | --- |
| nombre | 	Nombre del producto  | 	Cadenas de texto |
| fabricante 	| Nombre del fabricante | 'Kelloggs', 'Quaker Oats', 'General Mills', 'Nabisco', etc  |
| calorias 	| Calorías por porción. 	| Numéricos |
| proteina |	Gramos de proteína. 	|Numéricos |
| grasa |	Gramos de grasas saturadas. 	| Numéricos|
| sodio |	Miligramos de sodio. 	|Numéricos |
| fibra dietaria |	Gramos de fibra dietaria. 	| Numéricos|
| carbohidratos |	Gramos de carbohidratos complejos. 	|Numéricos |
| potasio |	Miligramos de potasio. 	|Numéricos |
| vitaminas y minerales |	Porcentaje de vitaminas y minerales. 	|Numéricos |



En este quiz usted debe realizar un proceso de análisis de datos con *Python* con el objetivo de practicar los conceptos y habilidades aprendidas de estadística inferencial.

> **Nota:** Esta tarea va a ser calificada en la plataforma **[UNCode](https://juezun.github.io/)**. Para esto, en cada ejercicio se indicará si es calificable o no, también los lugares donde debe escribir su código sin modificar lo demás con un aproximado de cantidad de líneas a escribir. No se preocupe si su código toma más líneas, esto es simplemente un aproximado destinado a que pueda replantear su estrategia si el código está tomando más de las esperadas. No es un requisito estricto y soluciones más largas también son válidas. Al finalizar, para realizar el envío (*submission*), descargue el notebook como un archivo **`.ipynb`** y haga su entrega a través de la plataforma de aprendizaje.

Ejecute la siguiente celda para importar las librerías.

In [ ]:
# Importar librerías
import pandas as pd
import numpy as np
import scipy
from scipy import stats
import statsmodels.api as sm

In [ ]:
#TEST_CELL
!python --version
print('Pandas', pd.__version__)
print('NumPy', np.__version__)
print('SciPy', scipy.__version__)
print('statsmodels', sm.__version__)

Python 3.7.14
Pandas 1.3.5
NumPy 1.21.6
SciPy 1.7.3
statsmodels 0.12.2


Este material fue realizado con las siguientes versiones:

- Python 3.6.9
- Pandas: 1.1.5
- NumPy: 1.19.5
- SciPy: 1.4.1
- statsmodels: 0.10.2


> **Nota:** Recuerde usar los alias y convenciones de la celda anterior en su código. UNCode no tendrá en cuenta librerías que importe en otras celdas y podrían afectar el tiempo de ejecución de los problemas. Estas son:
  *  **Pandas**: **`pd`**
  *  **NumPy**: **`np`**
  *  **SciPy stats**: **`stats`**
  *  **statsmodels**: **`sm`**



## **0.  Leer el archivo de datos**
---
> **IMPORTANTE:** 

  1. Por favor descargue el archivo con el conjunto de datos desde el siguiente enlace: **[cerealsquiz.csv](https://raw.githubusercontent.com/JuezUN/datasets/master/cerealsquiz.csv)**. 
  
  2. En el enlace, haga clic derecho y seleccione la opción **"Guardar como..."**.

  3. Cargue este archivo en su sistema de archivos de **Google Colaboratory**. Para hacer esto:
    
    * Haga clic donde aparece el icono del directorio en la parte izquierda de la ventana en *Google Colaboratory* (resaltado en azul en la siguiente imagen con el número 1).
    * Después, haga clic en el icono **"Subir"** (resaltado en azul en la siguiente imagen con el número 2).
    * Seleccione el archivo **`titanic.csv`** que previamente descargó y haga clic en **"Aceptar"**.

<img src = "https://drive.google.com/uc?export=view&id=13W59jfdOpAn_DYIjpXt4WPBZiU7BlRGY" alt = "Sistema archivos colab" width = "70%">  </img>

4. Ejecute la siguiente celda para cargar el conjunto de datos dentro del DataFrame de *pandas* llamado **`cereal_df`**:

In [ ]:
### EJECUTAR ESTA CELDA SIN MODIFICARLA. SI FALLA, DEBE SEGUIR EL PROCEDIMIENTO DESCRITO ANTES.
cereal_df = pd.read_csv('cerealsquiz.csv')
cereal_df.head()

nombre      fabricante  calorias  proteina  grasa  \
0                  100%_Bran         Nabisco        70         4      1   
1          100%_Natural_Bran     Quaker Oats       120         3      5   
2                   All-Bran        Kelloggs        70         4      1   
3  All-Bran_with_Extra_Fiber        Kelloggs        50         4      0   
4             Almond_Delight  Ralston Purina       110         2      2   

   sodio  fibra dietaria  carbohidratos  azúcar  potasio  \
0    130            10.0            5.0       6      280   
1     15             2.0            8.0       8      135   
2    260             9.0            7.0       5      320   
3    140            14.0            8.0       0      330   
4    200             1.0           14.0       8       -1   

   vitaminas y minerales  
0                     25  
1                      0  
2                     25  
3                     25  
4                     25

In [ ]:
#TEST_CELL
cereal_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   nombre                 74 non-null     object 
 1   fabricante             74 non-null     object 
 2   calorias               74 non-null     int64  
 3   proteina               74 non-null     int64  
 4   grasa                  74 non-null     int64  
 5   sodio                  74 non-null     int64  
 6   fibra dietaria         74 non-null     float64
 7   carbohidratos          74 non-null     float64
 8   azúcar                 74 non-null     int64  
 9   potasio                74 non-null     int64  
 10  vitaminas y minerales  74 non-null     int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 6.5+ KB


No se preocupe por el archivo del dataset en ***UNCode***, el ambiente de calificación ya cuenta con este archivo para calificar sus ejercicios.

## **1. Valores nutricionales medios con confianza**
---
Usted es parte de un equipo que está trabajando en un análisis nutricional de la muestra de productos recolectada en el *dataset* de cereales. En un primer acercamiento se le encomienda la tarea de encontrar el valor promedio, en forma de intervalo de confianza, de la información nutricional de una variable dada (por ejemplo, el total de azúcar o calorias) de los productos de un fabricante específico de cereales.

Para esto, deberá definir la función **`valor_medio_intervalo`**, que tomará como entrada el nombre del **`fabricante`**, la columna o **`variable`** sobre la que debe realizar el cálculo y el nivel de **`confianza`** deseado para el cálculo del intervalo.

**Entradas:**
  * **`fabricante`**: Nombre del fabricante (**_Kelloggs_, _Quaker Oats_, _General Mills_, etc**).
  * **`variable`**: Nombre de la variable numérica sobre la que se realiza el cálculo (**azúcares, grasa, proteina, etc**).
  * **`confianza`**: Nivel **$\beta$** de confianza del intervalo.

**Salidas:**
  * **`inicio`**: Límite inferior del intervalo de confianza. 
  * **`final`**:  Límite superior del intervalo de confianza. 


Por ejemplo, si un miembro del equipo desea conocer el valor medio de **azúcar** del fabricante ***Kelloggs*** con un $95\%$ de confianza, el resultado de la ejecución debería ser el siguiente intervalo:

```python
>>> valor_medio_intervalo('Kelloggs', 'azúcar', 0.95)
(5.618939147403277, 9.511495635205419)
```

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>
<p>

* Recuerde la distinción entre nivel de **confianza** ($\beta$) y nivel de  **significancia** ($\alpha$).
* Puede realizar selección condicional en un eje y selección por etiquetas en otro con el atributo **`.loc`** para obtener el *dataset* seleccionando únicamente con los datos de interés.
* Consulte el material de estadística inferencial para saber cómo realizar un intervalo de confianza con **`statsmodels`**. No es necesario que utilice el método analítico.
</p>

In [ ]:
# FUNCIÓN CALIFICADA valor_medio_intervalo: 

def valor_medio_intervalo(fabricante, variable, confianza):
  ### ESCRIBA SU CÓDIGO AQUÍ ### (~ 3 líneas de código)
  subconjunto = (cereal_df.loc[cereal_df["fabricante"]==fabricante])[variable]
  # Seleccione únicamente los datos de interés (fabricante, variable) a partir del dataset 'cereal_df'
  inicio, final  =  sm.stats.DescrStatsW(subconjunto).tconfint_mean(alpha = 0.05)  # Ejecute la función estadística necesaria para obtener el intervalo de confianza.
  return inicio, final
  ### FIN DEL CÓDIGO ###

In [ ]:
#TEST_CELL
valor_medio_intervalo('Kelloggs', 'calorias', 0.95)

(99.08751461234769, 118.3037897354784)

**Salida esperada:**
```python
(99.08751461234769, 118.3037897354784)
```

## **2. ¿Existe alguna diferencia nutricional significativa entre los productos de *Kelloggs* y *General Mills*?**
---
Como parte del proceso de análisis se decide identificar si un fabricante ofrece productos cuyos valores nutricionales medios presenten diferencias significativas con respecto a los ingredientes y valores nutricionales de otro fabricante. En particular, tras un análisis exploratorio previo, se decidió explorar estas diferencias específicamente entre los fabricantes *Kelloggs* y *General Mills*. Esto obedece a que al explorar el conteo de valores por fabricante, se tiene que estos ofrecen un número similar de productos y son los más representativos en el mercado de cereales identificado.

In [ ]:
#TEST_CELL
cereal_df['fabricante'].value_counts()

Kelloggs                       23
General Mills                  22
Quaker Oats                     8
Post                            8
Nabisco                         6
Ralston Purina                  6
American Home Food Products     1
Name: fabricante, dtype: int64

Por otro lado, si calculamos los valores medios de las variables numéricas agrupando por fabricante podemos notar algunas diferencias notables en varias de las variables medidas. 

**¿Alguna de estas diferencias es estadísticamente significativa?**

In [ ]:
#TEST_CELL
cereal_df.groupby('fabricante').mean().loc[['Kelloggs', 'General Mills']]

calorias  proteina     grasa       sodio  fibra dietaria  \
fabricante                                                                  
Kelloggs       108.695652  2.652174  0.608696  174.782609        2.739130   
General Mills  111.363636  2.318182  1.363636  200.454545        1.272727   

               carbohidratos    azúcar     potasio  vitaminas y minerales  
fabricante                                                                 
Kelloggs           15.130435  7.565217  103.043478              34.782609  
General Mills      14.727273  7.954545   85.227273              35.227273

En este ejercicio deberá escribir la función **`cereales_hipotesis_media`**. Esta función realiza un test de hipótesis sobre la diferencia de medias de una **`variable`** dada, con un nivel de **`confianza`** deseado, para los fabricantes ***Kelloggs*** y ***General Mills***. A partir de los resultados del test de hipótesis debe determinar:

*  Si se puede llegar o no a una **`conclusión`** significativa con el valor de confianza deseado.
*  El **`p-valor`** de la prueba.
*  El nombre del fabricante con **`mayor`** y **`menor`** valor según la media muestral, en ese orden.


**Entradas:**
  * **`variable`**: Nombre de la variable numérica sobre la que se realiza el cálculo (**azúcares, grasa, proteína, etc.**).
  * **`confianza`**: Nivel **$\beta$** de confianza del intervalo.

**Salidas:**
  * **`conclusión`**: Valor Booleano (`True` o `False`) indicando si hay una diferencia significativa. 
  * **`p_valor`**:  El **`p-valor`** de la prueba. 
  * **`mayor`**:  El nombre del fabricante con el valor mayor según la media muestral. 
  * **`menor`**:  El nombre del fabricante con el valor menor según la media muestral. 

Por ejemplo, si se deseara comparar la cantidad de **azúcar** con un valor de confianza del $95\%$, el resultado de la ejecución debería ser el siguiente:


```python
>>> cereales_hipotesis_media('azúcar', 0.95)
(False, 0.7577470989748843, 'General Mills', 'Kelloggs')
```




<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>
<p>

* Recuerde la distinción entre **confianza** ($\beta$) y **significancia** ($\alpha$).
* Consulte el material de estadística inferencial para saber cómo realizar un test de hipótesis con **`scipy`**. No es necesario que utilice el método analítico.
* Tenga en cuenta que el test está diseñado para identificar si **existe una diferencia significativa**, y no se conoce ni hipotetiza cuál de las dos debería ser mayor. ¿Qué tipo de *hipótesis* es esta y qué relación tiene con la significancia utilizada?
* Considere el tamaño de las muestras y demás factores. ¿Qué prueba de hipótesis discutida y ejemplificada en el material guía es la más apropiada?
</p>

In [ ]:
# FUNCIÓN CALIFICADA cereales_hipotesis_media:
##realiza un test de hipótesis sobre la diferencia de medias de una variable dada, con un nivel de confianza deseado
def cereales_hipotesis_media(variable, confianza):
  # Seleccionamos los fabricantes que nos interesan
  kelloggs = cereal_df.loc[cereal_df['fabricante'] == 'Kelloggs']
  general_mills = cereal_df.loc[cereal_df['fabricante'] == 'General Mills']
  ### ESCRIBA SU CÓDIGO AQUÍ ### (~ 5 líneas de código)
  stat, pvalor = stats.ttest_ind(kelloggs.loc[:,variable], general_mills.loc[:,variable]) # Ejecute la prueba estadística más apropiada. 
  conclusion = True if pvalor <= (1-confianza) else False # Utilice el resultado de la prueba para determinar si la diferencia es significativa o no (conclusión).
  mayor = "General Mills" if general_mills.loc[:,variable].mean() > kelloggs.loc[:,variable].mean() else "Kelloggs"
  menor = "Kelloggs" if general_mills.loc[:,variable].mean() > kelloggs.loc[:,variable].mean() else "General Mills" 
  None  # Asigne el nombre de cada fabricante a la variable correspondiente de acuerdo al resultado. 
  ### FIN DEL CÓDIGO ###
  return conclusion, pvalor, mayor, menor

In [ ]:
#TEST_CELL
cereales_hipotesis_media('azúcar', 0.95)

(False, 0.7577470989748843, 'General Mills', 'Kelloggs')

**Salida esperada:**
```python
(False, 0.7577470989748843, 'General Mills', 'Kelloggs')
```

Puede usar la siguiente celda de pruebas para probar su función. En esta se lleva a cabo la prueba en todas las variables con un nivel de confianza del $90\%$.

In [18]:
#TEST_CELL
confianza = 0.9
print(f'Con un valor de confianza de {confianza}')
print('-------------------------------------------')
for variable in cereal_df.select_dtypes(np.number).columns: # select_dtypes para tener en cuenta solo variables numéricas.
  conclusion, pvalor, mayor, menor = cereales_hipotesis_media(variable, confianza)
  if (conclusion):
    print(f'Los productos de {mayor} tienen mayor cantidad de {variable} que los de {menor} con un p-valor de {pvalor:.4f}.\n') #  :.4f para aproximar a 4 decimales.
  else:
    print(f'No se puede afirmar que existe una diferencia en la cantidad de {variable}. (p-valor: {pvalor:.4f})\n')

Con un valor de confianza de 0.9
-------------------------------------------
No se puede afirmar que existe una diferencia en la cantidad de calorias. (p-valor: 0.6111)

No se puede afirmar que existe una diferencia en la cantidad de proteina. (p-valor: 0.3141)

Los productos de General Mills tienen mayor cantidad de grasa que los de Kelloggs con un p-valor de 0.0011.

No se puede afirmar que existe una diferencia en la cantidad de sodio. (p-valor: 0.2096)

Los productos de Kelloggs tienen mayor cantidad de fibra dietaria que los de General Mills con un p-valor de 0.0505.

No se puede afirmar que existe una diferencia en la cantidad de carbohidratos. (p-valor: 0.7344)

No se puede afirmar que existe una diferencia en la cantidad de azúcar. (p-valor: 0.7577)

No se puede afirmar que existe una diferencia en la cantidad de potasio. (p-valor: 0.4185)

No se puede afirmar que existe una diferencia en la cantidad de vitaminas y minerales. (p-valor: 0.9547)



**Salida esperada:**
```python
Con un valor de confianza de 0.9
-------------------------------------------
No se puede afirmar que existe una diferencia en la cantidad de calorias. (p-valor: 0.6111)

No se puede afirmar que existe una diferencia en la cantidad de proteina. (p-valor: 0.3141)

Los productos de General Mills tienen mayor cantidad de grasa que los de Kelloggs con un p-valor de 0.0011.

No se puede afirmar que existe una diferencia en la cantidad de sodio. (p-valor: 0.2096)

No se puede afirmar que existe una diferencia en la cantidad de fibra dietaria. (p-valor: 0.0505)

No se puede afirmar que existe una diferencia en la cantidad de carbohidratos. (p-valor: 0.7344)

No se puede afirmar que existe una diferencia en la cantidad de azúcar. (p-valor: 0.7577)

No se puede afirmar que existe una diferencia en la cantidad de potasio. (p-valor: 0.4185)

No se puede afirmar que existe una diferencia en la cantidad de vitaminas y minerales. (p-valor: 0.9547)
```

¿Cómo se puede interpretar este resultado? Por favor, siempre analice e interprete sus hallazgos.

**¡Felicitaciones!** Ha terminado el quiz. ¡Excelente trabajo!

## **Entrega**
Para entregar el notebook por favor haga lo siguiente:
1. Descargue el notebook (`Archivo` -> `Descargar .ipynb`).
2. Ingrese a la plataforma de aprendizaje.
3. Realice el envío del *notebook* que descargó en la tarea (o quiz) correspondiente.
4. Recuerde que si tiene algún error, puede hacer múltiples intentos. 

## **Créditos**
---

* **Profesor:** [Felipe Restrepo Calle](https://dis.unal.edu.co/~ferestrepoca/)
* **Asistentes docentes:**
  - Alberto Nicolai Romero Martínez
  - Miguel Angel Ortiz Marín

**Universidad Nacional de Colombia** - *Facultad de Ingeniería*
